// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.3
// source: proto/datanode/datanode.proto

package server

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataNodeSeverClient is the client API for DataNodeSever service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeSeverClient interface {
}

type dataNodeSeverClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeSeverClient(cc grpc.ClientConnInterface) DataNodeSeverClient {
	return &dataNodeSeverClient{cc}
}

// DataNodeSeverServer is the server API for DataNodeSever service.
// All implementations must embed UnimplementedDataNodeSeverServer
// for forward compatibility
type DataNodeSeverServer interface {
	mustEmbedUnimplementedDataNodeSeverServer()
}

// UnimplementedDataNodeSeverServer must be embedded to have forward compatible implementations.
type UnimplementedDataNodeSeverServer struct {
}

func (UnimplementedDataNodeSeverServer) mustEmbedUnimplementedDataNodeSeverServer() {}

// UnsafeDataNodeSeverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeSeverServer will
// result in compilation errors.
type UnsafeDataNodeSeverServer interface {
	mustEmbedUnimplementedDataNodeSeverServer()
}

func RegisterDataNodeSeverServer(s grpc.ServiceRegistrar, srv DataNodeSeverServer) {
	s.RegisterService(&DataNodeSever_ServiceDesc, srv)
}

// DataNodeSever_ServiceDesc is the grpc.ServiceDesc for DataNodeSever service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNodeSever_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DataNodeSever",
	HandlerType: (*DataNodeSeverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/datanode/datanode.proto",
}
